### PR TITLE
feat(forms): update forms to integrate with zoominfo and only use bus…

### PR DESCRIPTION
**Pull request by jomarmontuya**
…iness email as field

# Description

Modify the website forms to use single business email field only
Integrate zoomInfo to pre populate hidden fields in the website and post it to zoho

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list the simulator and android emulators used.

- [x] Manual Test

# Screenshots / Screen recording

image

Please add screenshots or recording if applicable

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by jomarmontuya** [comment]
image
image
image

**Review by ardeay — CHANGES_REQUESTED** [review]
Have you pulled the latest from stage? Also why 4000 lines have change?

**Comment by jomarmontuya** [comment]
@ardeay  it's because of the blocklisted email domains around 3.5k lines saved in a file

**Comment by ardeay** [comment]
Duhh on me @jomarmontuya thank you. Merged now

**Pull request merged**
