### PR TITLE
Fix/typo token & open manager button on instance & marketing footer

### LINKED ISSUE #1116: Marketing pages still need a footer
Marketing pages should still show the marketing footer

image

### LINKED ISSUE #1119: Add "Open Manager" button to instance cards
image

Add orange button to left of "preview" that says "Open Manager" that target blank open the manager url

### LINKED ISSUE #1126: Typo: Creating new access token
Image

After creating new access token in the APIs view, the spelling should be **_`retrieve`_**

### PR DESCRIPTION
**Pull request by glespinosa**

### CODE REVIEW

**Comment by glespinosa** [comment]
Open manager button link to manager ui
image
image

**Comment by glespinosa** [comment]
Marketting footer now shows on marketing page even it is logged in
image

**Comment by glespinosa** [comment]
App Footer will show only when logged in, in the accounts ui pages
image
image

**Comment by ardeay** [comment]
image
Make that a single line of Text. Remove Copy right symbol, z-index: 0 (to keep it behind things. Remove top gray border, transparent the background. Turn links the same color as text (so they are not blue)

**Comment by glespinosa** [comment]
> image
> 
> Make that a single line of Text. Remove Copy right symbol, z-index: 0 (to keep it behind things. Remove top gray border, transparent the background. Turn links the same color as text (so they are not blue)

image

**Pull request merged**
