### PR TITLE
Breadcrumb on the App Bar Module fix

### PR DESCRIPTION
**Pull request by darwin808**
Breadcrumb on the App Bar Module fix

### CODE REVIEW

**Comment by darwin808** [comment]
image
image
image

**Comment by ardeay** [comment]
Switch `home` word  for the home icon 
image

**Comment by darwin808** [comment]
image

**Comment by ardeay** [comment]
Please follow this https://mui.com/material-ui/react-breadcrumbs/#active-last-breadcrumb

**Comment by ardeay** [comment]
For the icon treatment, use this style but without the text for the home button https://github.com/zesty-io/nextjs-website/pull/527#issuecomment-1134712099

**Pull request merged**
