### PR TITLE
style(shell ,profile,instances styling): shell ,profile,instances styling)

### LINKED ISSUE #854: Accounts: shell design update request
Update the old look 
image
 to look like this 
image

Across instance and profile for every view

### LINKED ISSUE #855: Accounts: Instances Left Bar Design
make the existing design 
image

Look like this
image

Here is a video walk through of the changes

https://www.loom.com/share/9807d344e4684750aec3c4f082336306

### PR DESCRIPTION
**Pull request by glespinosa**
Update on styling on shell, instances and profile containers

### CODE REVIEW

**Comment by glespinosa** [comment]
Issues: https://github.com/zesty-io/website/issues/855 & https://github.com/zesty-io/website/issues/854
image
image

**Review by ardeay — CHANGES_REQUESTED** [review]
Adjust bottom spacing of the title so the top spacing and bottom space are equal

**Comment by ardeay** [comment]
Please make this select in the app bar: size small 
image

**Comment by glespinosa** [comment]
New select with small size, I added padding bottom and top on the box because it doesn't look good without one.
image

Without padding
image

Equal top and bottom padding
image

**Comment by ardeay** [comment]
@glespinosa please resolve conflicts

**Comment by ardeay** [comment]
nice work @glespinosa

**Pull request merged**
