### PR TITLE
fix(fix teams update option): fix teams update option

### LINKED ISSUE #2041: [Accounts - UI] Button for Manage Teams is missing
### Description

Looking from the old UI, you can modify teams in the accounts ui by clicking the gear icon ⚙️

image

However from the new Accounts UI, there is no button for managing the existing teams

image

This feature is necessary to update the current docs with the new UI: https://zesty.org/services/accounts-ui/teams

### Reproduction URL

https://www.zesty.io/teams/

### Reproduction steps

```bash
N/A
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by glespinosa**
# Description

The issue here is that the gear icon is not present for editing of teams that owns by a user

# Fixes issue
#1944 

# Screenshots / Screen recording

[screencast-test.zesty.io_3000-2023.11.16-17_50_24.webm](https://github.com/zesty-io/website/assets/44116036/8a279c7c-6725-4f1c-a8df-4575c493d7c8)

### CODE REVIEW

**Comment by darwin808** [comment]
@glespinosa  can you check the color violet of the button in the video ?

**Comment by glespinosa** [comment]
> @glespinosa can you check the color violet of the button in the video ?

the color violet here is the default color primary i think of the SWAL 
image
would you like me to change that color?

**Comment by darwin808** [comment]
> > @glespinosa can you check the color violet of the button in the video ?
> 
> the color violet here is the default color primary i think of the SWAL image would you like me to change that color?

can we sync that to our theme

**Comment by glespinosa** [comment]
> > > @glespinosa can you check the color violet of the button in the video ?
> > 
> > 
> > the color violet here is the default color primary i think of the SWAL image would you like me to change that color?
> 
> can we sync that to our theme

nope , it is we either target its css or use a different modal dialog that is using mui, or use this package https://www.npmjs.com/package/material-ui-confirm

**Comment by glespinosa** [comment]
> > > > @glespinosa can you check the color violet of the button in the video ?
> > > 
> > > 
> > > the color violet here is the default color primary i think of the SWAL image would you like me to change that color?
> > 
> > 
> > can we sync that to our theme
> 
> nope , it is we either target its css or use a different modal dialog that is using mui, or use this package https://www.npmjs.com/package/material-ui-confirm

I tried using the material-ui-confirm
image

**Review by darwin808 — APPROVED** [review]

**Pull request merged**
