### PR TITLE
feat(docs): add search inside nav tree and modify the algolia search …

### PR DESCRIPTION
**Pull request by jomarmontuya**
…modal design

### CODE REVIEW

**Review by giseleblair — COMMENTED** [review]
@jomarmontuya please include screenshots or video of functionality

**Comment by jomarmontuya** [comment]
[screen-capture.webm](https://user-images.githubusercontent.com/61284357/221879957-ed7b8dfb-b08d-45af-9aa8-0ce1189108f1.webm)
@giseleblair

**Comment by jomarmontuya** [comment]
I merged to this branch darwin latest  PR for aloglia 2nd index zesty org

**Review by giseleblair — CHANGES_REQUESTED** [review]
Please remove unused vars

**Review by giseleblair — APPROVED** [review]

**Pull request merged**
