### PR TITLE
Landing pages autolayout

### PR DESCRIPTION
**Pull request by jomarmontuya**

### CODE REVIEW

**Comment by jomarmontuya** [comment]
image
This is the only custom component defined in the hero section,

the rest are autolayout controlled components 

@ardeay

**Comment by ardeay** [comment]
@darwin808 @jomarmontuya why are these tests failed?
image

**Comment by jomarmontuya** [comment]
@ardeay  fix build issues

**Comment by jomarmontuya** [comment]
test page running on dev branch -> https://zesty-dev-website-m3rbwjxm5q-uc.a.run.app/test-2023-landing-page/

**Comment by ardeay** [comment]
@jomarmontuya is there schema for this?

**Review by ardeay — APPROVED** [review]

**Pull request merged**
