### PR TITLE
Accounts Instances Overview Tab 

### LINKED ISSUE #894: Instances: Overview Page
Overview page of each instance's page

### PR DESCRIPTION
**Pull request by darwin808**
image

### CODE REVIEW

**Comment by ardeay** [comment]
Hi @darwin808 can you share the wireframe or reference you are using to build this view.

**Comment by ardeay** [comment]
Pause on this @darwin808 , i think the wireframe may be placed incorrectly https://github.com/orgs/zesty-io/projects/47

**Comment by ardeay** [comment]
This wireframe is intended for the dashboard component, the component that will replace the normal Homepage.js view if the user is logged in @darwin808 @bltarkany

**Comment by bltarkany** [comment]
@darwin808 redrafted overview page for an instance on this issue:
https://github.com/zesty-io/website/issues/894#issuecomment-1231933019

**Comment by darwin808** [comment]
image
image
image

**Comment by bltarkany** [comment]
@darwin808 the layout looks good to me - @giseleblair / @ardeay do you want anything else included on the overview page?

**Comment by giseleblair** [comment]
Looks good to me!

**Comment by ardeay** [comment]
@darwin808 please resolve conflicts

**Pull request merged**
