### PR TITLE
fix(next-js integration page): fix layout issues on nextjs integratio…

### LINKED ISSUE #1328: The background doesn't contain the whole box
The background doesn't contain the whole box
image

### PR DESCRIPTION
**Pull request by jomarmontuya**
…n page

### CODE REVIEW

**Comment by jomarmontuya** [comment]
image

**Comment by glespinosa** [comment]
@jomarmontuya  still having this behavior in large size
image

**Review by glespinosa — CHANGES_REQUESTED** [review]
still having this behavior in large size
image

**Comment by jomarmontuya** [comment]
@glespinosa what screen width is that and screen zoom?


Checked on my end currently using 3140 x 2160 + 25% zoom here's the output

image

**Comment by glespinosa** [comment]
> @glespinosa what screen width is that and screen zoom?
> 
> Checked on my end currently using 3140 x 2160 + 25% zoom here's the output
> 
> image

@jomarmontuya looks good on me now but when in darkmode I cant see the logos
image

**Comment by jomarmontuya** [comment]
@glespinosa  should be fixed now, please confirm 

image

**Review by glespinosa — APPROVED** [review]

**Comment by glespinosa** [comment]
> @glespinosa should be fixed now, please confirm
> 
> image

nice! its good now.

**Review by darwin808 — APPROVED** [review]

**Pull request merged**
