### PR TITLE
Account Webhooks Tab Updates 

### PR DESCRIPTION
**Pull request by darwin808**
## Changes 
- Webhooks tab initialize
- refactor of locale tab 

image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by ardeay** [comment]
In the webhook table output, omit the ZUID, add columns: "URL", "Method"

**Comment by ardeay** [comment]
Have a webhook view button, next to test, "view" sweetAlert the output into a clean key:value table

**Comment by ardeay** [comment]
Change "test webhook" to "test"

**Comment by ardeay** [comment]
Change "submit" to "Create Webhook"

**Review by ardeay — APPROVED** [review]

**Comment by ardeay** [comment]
Please add column from "Action" which show publish/create etc..

Combine column "Action" in a column with no header value that includes all three buttons using a button group for "view" and "test" https://github.com/zesty-io/website/pull/825 and a stand alone button for delete. Use color="error" for delete, use a stack to connect the button group and button    https://mui.com/material-ui/react-stack/#direction

**Comment by darwin808** [comment]
@ardeay 
image

**Pull request merged**
