### PR TITLE
update(zestydocs.js): update how the content is being rendered

### PR DESCRIPTION
**Pull request by arzljames**

### CODE REVIEW

**Review by giseleblair — COMMENTED** [review]
Why do we need `MuiMarkdown from 'markdown-to-jsx`  ?
If the `content` objects returns a string of html, what is the purpose of `MuiMarkdown` ?

**Comment by arzljames** [comment]
> Why do we need `MuiMarkdown from 'markdown-to-jsx` ? If the `content` objects returns a string of html, what is the purpose of `MuiMarkdown` ?

I initially used the **dangerouslySetInnerHTML** props but then I saw some components using **MuiMarkdown** to render WYSIWYG content. But yeah, maybe I should revert it to the previous one

**Comment by giseleblair** [comment]
@arzljames which components are using markdown content?

**Comment by arzljames** [comment]
I found it inside the DarkBleCta.js but I'm not sure if it is being used
image

image

**Comment by arzljames** [comment]
Alright, I'll just use regular div and dangerouslySetInnerHTML props and then will update this PR.

**Comment by giseleblair** [comment]
@arzljames note that your screenshot is from another content model. We are only working on the Zesty Docs model

**Comment by arzljames** [comment]
> @arzljames note that your screenshot is from another content model. We are only working on the Zesty Docs model

Got it @giseleblair

**Comment by arzljames** [comment]
Updated the PR @giseleblair please kindly check again. Thank you

**Pull request merged**
