### PR TITLE
Launch App / start page 

### PR DESCRIPTION
**Pull request by ardeay**

### CODE REVIEW

**Comment by darwin808** [comment]
@ardeay i have update and make it in /start in different folder

**Review by ardeay — COMMENTED** [review]
- remove  public/assets/images/join/project-details.png, that file reference should be used by the template data from headless marketplace
- parsely is in correct spelling, please update assets and references to: Parsley
- delete onboarding.js marketer.js developer.js manager.js and components copied that aren't used

**Comment by ardeay** [comment]
Move Pendo script from WelcomeScreen.js to execute just after user sign creation

image

**Comment by darwin808** [comment]
## Scenario 1
https://user-images.githubusercontent.com/71545960/193301455-cc926a94-2797-463c-9c2d-52a9712c3f7f.mp4

## Scenario 2 

https://user-images.githubusercontent.com/71545960/193301953-902ec6d3-3f28-490a-9309-7b0e8cc67039.mp4




## Scenario 3 

https://user-images.githubusercontent.com/71545960/193301556-a6cac207-9e96-4a60-9284-805564e21155.mp4

## Scenario 4 

https://user-images.githubusercontent.com/71545960/193301586-7ddf5de8-930d-4ab6-983d-484fe78e23df.mp4

**Pull request merged**
