### PR TITLE
Hotfix website redirect issues

### PR DESCRIPTION
**Pull request by jomarmontuya**

### CODE REVIEW

**Comment by jomarmontuya** [comment]
#### Issue 
Website redirects is not working ->https://github.com/zesty-io/website/issues/1049

#### Findings
Logical error on fetchRedirects function, stage and production env url's are not accessible from the file.

#### Solution
1. assign stage and production url directly from the file. This will only be used once during build time
2. check source path if startswith '/' then add to redirect, otherwise skip it to avoid crash during build time but send console warning on logs with details

#### Notes
The fetchRedirect function only runs once on build time to fetch all the redirect url's from the CMS, therefore changes on the CMS redirects might not work in realtime, cause the site's needs to be rebuild in order to fetch new url's

**Comment by jomarmontuya** [comment]
[Untitled video - Screen Recording - 10_26_2022, 12_16_18 AM.webm](https://user-images.githubusercontent.com/61284357/197827775-2fe2f42f-28e5-45d2-ad39-d9411cde04ae.webm)

**Review by ardeay — CHANGES_REQUESTED** [review]
@jomarmontuya please send this to the DEV pipeline for testing prior to a stage PR

**Review by darwin808 — APPROVED** [review]

**Comment by jomarmontuya** [comment]
@ardeay This PR is already on dev branch I and Katie tested it and seems to work well kindly see link here

https://zesty-dev-website-m3rbwjxm5q-uc.a.run.app/

Thank you

**Pull request merged**
