### PR TITLE
Locales tab

### LINKED ISSUE #805: Accounts: Locales Tab
Locales (langs) should be a  MUI table of current locales (data from from langs endpoint in instances https://instances-api.zesty.org/#25872fe9-ce04-48f1-b0ba-91e2b8f399ee)

Each table row should show an add locale button, which triggers pop-up, and add a locale. Each row shoudl tell which language is active and what is the primary language. This info comes from get langs https://instances-api.zesty.org/#9ef38bd1-59e6-4d58-b83c-d719842fc2f0

Local tables should have a "activate" button and "delete button" 
Actviate: use the put command, see docs https://instances-api.zesty.org/#a8e6496e-c430-4a75-9ab3-8479b74e479c
Delete: Trigger popup warning dialog, allow user to confirm delete, or cancel, before sending delete api call https://instances-api.zesty.org/#d554fdf0-b998-4ff4-8129-092608075ebb

### PR DESCRIPTION
**Pull request by glespinosa**
> Creating layout for local tab
> Consuming api  data to display in table
> Functionalities ( Add, delete, activate/deactivate)

### CODE REVIEW

**Comment by ardeay** [comment]
@glespinosa please post screenshots of the UI

**Comment by glespinosa** [comment]
### Demo
When adding a locale on this instance it doesnt show the error.
But still having error when trying to delete a locale

[locales tab.webm](https://user-images.githubusercontent.com/44116036/184886872-1c8b884a-cbeb-4853-a70d-373b5c4ecba9.webm)


### When adding a locale a dialog box is prompt
image

### Adding invalid locale a notification will prompt
image

### Layout
image

image

**Comment by ardeay** [comment]
For the table, follow this styling 
image

https://mui.com/material-ui/react-table/#customization

Except make the table header plain white with the palette main text color

**Comment by glespinosa** [comment]
> For the table, follow this styling image
> 
> https://mui.com/material-ui/react-table/#customization
> 
> Except make the table header plain white with the palette main text color

@ardeay 
### Updated table style
image

**Pull request merged**
