### PR TITLE
fix(buttons,navbar,teams,instances)

### LINKED ISSUE #1010: Accounts Instances Page: move instance name to the top of the card and add links to to open manager or edit settings
In the Grid view of the Instances page move the instances' name in the cards to the top of the card - next to the favorite star. 

In the footer of the cards add a link to open the instance in the content manager & a link to the instances settings page. 

Image

### LINKED ISSUE #1030: Accounts: Teams page add border on cards and drop elevation
On the Teams Page the individual teams cards Should have a border and the elevation should be dropped to stay consist with elevations across the app.

Image

### LINKED ISSUE #1031: Accounts: Primary Navbar - links should be highlighted when active
In the primary navbar the links should be highlighted and bold to indicate it is the active page
 

Image

### LINKED ISSUE #1041: Locales Page - hide the add button.

### LINKED ISSUE #1045: Accounts: Buttons -- all buttons need to be orange or outlined with orange text

### PR DESCRIPTION
**Pull request by glespinosa**
https://github.com/zesty-io/website/issues/1010
image

https://github.com/zesty-io/website/issues/1041
image
https://github.com/zesty-io/website/issues/1031
image
https://github.com/zesty-io/website/issues/1030
image

### CODE REVIEW

**Comment by ardeay** [comment]
@glespinosa please pull latest accounts and resolve conflict.

Also, change the setting link to "Preview" which open webengine rootdomain  for that instance

Make setting link the COG icon, aligned right

**Comment by ardeay** [comment]
image
Move Create Instance button to the right of the dropdown

Change legacy button to variant="outlined"

**Comment by ardeay** [comment]
Make both legacy and create button size="small"

**Comment by glespinosa** [comment]
image

**Comment by ardeay** [comment]
image

Add exit icon to legacy accounts button, make legacy accounts button text and outline grey 
image

**Comment by glespinosa** [comment]
image
image

**Pull request merged**
