### PR TITLE
Bug/large screen issues

### LINKED ISSUE #1326: Darkmode layout problem in Products Page when in large screen size
Headless CMS Page (/solutions/headless-cms/)
Hybrid CMS (/solutions/hybrid-cms/)

image
image

Repetition of background
Solutions (/solutions)
image

Having scrolling when large screen size and same issues above
Digital Experience Platform (solutions/digital-experience-platform/)
image

Integrations Menu doesn't have attached link / page to it?
image

DXP Enterprise (/solutions/digital-experience-platform/dxp-enterprise/)
image

When in darkmode the text disappears
image

### PR DESCRIPTION
**Pull request by jomarmontuya**
- [x] /solutions/headless-cms/
- [x] /solutions/hybrid-cms/
- [x] /solutions
- [x] /solutions/digital-experience-platform/
- [x] Integrations Menu doesn't have attached link / page to it?
- [x] /solutions/digital-experience-platform/dxp-enterprise/
- [x] When in darkmode the text disappears

### CODE REVIEW

**Comment by jomarmontuya** [comment]
screencapture-localhost-3000-solutions-headless-cms-2022-11-11-21_48_58

**Comment by jomarmontuya** [comment]
screencapture-localhost-3000-solutions-headless-cms-2022-11-11-22_00_48

**Comment by jomarmontuya** [comment]
screencapture-localhost-3000-solutions-hybrid-cms-2022-11-14-20_28_09

**Comment by jomarmontuya** [comment]
image

**Comment by jomarmontuya** [comment]
image

**Comment by jomarmontuya** [comment]
image

**Review by glespinosa — COMMENTED** [review]
@jomarmontuya all changes I requested are good, one question on the behavior on this component , is the toggle images should be on the left side instead in the center when in smallest screen size?

[screencast-test.zesty.io_3000-2022.11.14-21_35_17.webm](https://user-images.githubusercontent.com/44116036/201674276-b3bb5438-a4f9-418e-9690-cfb3c31c5fe5.webm)

**Review by glespinosa — APPROVED** [review]
nice!

**Review by darwin808 — APPROVED** [review]

**Pull request merged**
