### PR TITLE
fix(security.js): unhide and disable authy

### PR DESCRIPTION
**Pull request by darwin808**
image

### CODE REVIEW

**Comment by giseleblair** [comment]
@darwin808 can you share a screenshot of what the interface looks like when the user already has 2FA enabled

**Comment by darwin808** [comment]
image
@giseleblair i dont have authy enabled

**Comment by giseleblair** [comment]
@darwin808 the user should be able to disable 2fa (but they cannot enable it)

**Comment by darwin808** [comment]
image

**Pull request merged**
