### PR TITLE
🚀 stage to production

### PR DESCRIPTION
**Pull request by darwin808**
## Changelog 

- fix(homepage): SSO login issue

### CODE REVIEW

**Review by ardeay — APPROVED** [review]

**Comment by gtllien** [comment]
@giseleblair I tested the login using MS SSO and it seems working on my end though it takes about a second before it redirects to dashboard:
chrome_Ms2PSCu7UM

**Comment by giseleblair** [comment]
@darwin808 please look into this redirect lag

**Comment by gtllien** [comment]
Tested using Google SSO and was able to replicate the issue - it keeps on redirecting back to login page:

chrome_BLebiQVWoP

**Comment by giseleblair** [comment]
@gtllien thank you, test with github too please

**Comment by gtllien** [comment]
Also tried logging in using Github but I'm not able to get in:

https://github.com/zesty-io/website/assets/112954373/f20d182c-c388-4005-b12b-7748bc77e08b

**Pull request merged**
